version: '2.3'
services:
  todolist:
    container_name: todolist_webapp
    build: .
    depends_on:
      - mysql_server
    links:
      - 'mysql_server'
    expose:
      - '8080'
  mysql_server:
    container_name: mysql_server
    restart: always
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'todolistpassword'
