version: '2.3'
services:
  todolist:
    container_name: todolist_webapp
    build: .
    depends_on:
      - mysql_server
    network_mode: 'host'
  mysql_server:
    container_name: mysql_server
    restart: always
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'todolistpassword'
    network_mode: 'host'
